1\. Write the following as a list comprehension

In [1]:
# 1
ans = []
for i in range(3):
    for j in range(4):
        ans.append((i, j))
print (ans)

ans = [(i, j) for i in range(3) for j in range(4)]
print(ans)

# 2
ans = map(lambda x: x*x, filter(lambda x: x%2 == 0, range(5)))
print (list(ans))

ans=[x**2 for x in range(5) if x%2==0]
print(ans)

[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]
[0, 4, 16]
[0, 4, 16]


2\. Convert the following function into a pure function with no global variables or side effects

In [2]:
'''
x = 5
def f(alist):
    for i in range(x):
         alist.append(i)
    return alist

alist = [1,2,3]
ans = f(alist)
print (ans)
print (alist) # alist has been changed!
'''

x = 5
def f(alist,y):
    alist=[x+1-1 for x in alist]
    for i in range(y):
         alist.append(i)
    return alist

alist = [1,2,3]
ans = f(alist,x)
print (ans)
print (alist)

[1, 2, 3, 0, 1, 2, 3, 4]
[1, 2, 3]


3\. Write a `decorator` hello that makes every wrapped function print “Hello!”, i.e. something like:

```python
@hello
def square(x):
    return x*x
```



In [3]:
def hello(func):
    def wrapper(x):
        print("Hello!")
        return func(x)
    return wrapper

@hello
def square(x):
    return x*2

print(square(2))

Hello!
4


4\. Write the factorial function so that it a) does and b) does not use recursion.

In [4]:
def factorial1(n):                        # without recursion
    f=1
    while n>1:
        f*=n
        n-=1
    return f
print(factorial1(5))

def factorial2(n):                        # with recursion
    if n>1:
        return(n*factorial2(n-1))
    else:
        return(1)
print(factorial2(5))

120
120


5\. Use HOFs (zip in particular) to compute the weight of a circle, a disk and a sphere, assuming different radii and different densities:

```python
densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
radii = [1,2,3]
```

where the entries of the dictionary's values are the linear, superficial and volumetric densities of the materials respectively.

In particular define a list of three lambda functions using a comprehension that computes the circumference, the area and the volume for a given radius.


In [5]:
import numpy as np
densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
radii = [1,2,3]

cav=[np.array([list(map(lambda r:2*np.pi*r,radii))]) ,np.array([list(map(lambda r:np.pi*r**2,radii))]), np.array([list(map(lambda r:4/3*np.pi*r**3,radii))])]
den=[[densities["Al"][0],densities["Fe"][0],densities["Pb"][0]],[densities["Al"][1],densities["Fe"][1],densities["Pb"][1]],[densities["Al"][2],densities["Fe"][2],densities["Pb"][2]]]

result=[]
for x, y in zip(cav,den):
    result.append(x*y)

print("Peso circonferenze:  r=1 <-> Al , r=2 <-> Fe, r=3 <-> Pb")
for x in result[:][0]:
    print(x)
print("Peso dischi:  r=1 <-> Al , r=2 <-> Fe, r=3 <-> Pb")
for x in result[:][1]:
    print(x)
print("Peso sfere:  r=1 <-> Al , r=2 <-> Fe, r=3 <-> Pb")
for x in result[:][2]:
    print(x)

Peso circonferenze:  r=1 <-> Al , r=2 <-> Fe, r=3 <-> Pb
[  3.14159265  37.69911184 282.74333882]
Peso dischi:  r=1 <-> Al , r=2 <-> Fe, r=3 <-> Pb
[  3.14159265  50.26548246 565.48667765]
Peso sfere:  r=1 <-> Al , r=2 <-> Fe, r=3 <-> Pb
[   8.37758041  167.55160819 3392.92006588]


6\. Edit the class defintion to add an instance attribute of is_hungry = True to the Dog class. Then add a method called eat() which changes the value of is_hungry to False when called. Figure out the best way to feed each dog and then output “My dogs are hungry.” if all are hungry or “My dogs are not hungry.” if all are not hungry. The final output should look like this:

`I have 3 dogs. 
Tom is 6. 
Fletcher is 7. 
Larry is 9. 
And they're all mammals, of course. 
My dogs are not hungry.
`

```python
# Parent class
class Dog:

    # Class attribute
    species = 'mammal'

    # Initializer / Instance attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)

    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)

# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)
```

In [37]:
# Parent class
class Dog:

    # Class attribute
    species = 'mammal'

    # Initializer / Instance attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.is_hungry=True

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)

    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)
    
    def eat(self):
        self.is_hungry=False

# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)
    
Tobia=RussellTerrier("Tobia",7)                        # definisco i miei cani
Maya=RussellTerrier("Maya",3)
Argo=Bulldog("Argo",13)
list_dog=[Tobia, Maya, Argo]                           # tutti i miei cani devono essere inseriti nella lista

def feed_all_dogs ():                                  # faccio mangiare tutti i miei cani
    global list_dog
    for x in list_dog:
        x.eat()

def check_status (list_dog):                           # controllo se sono tutti affamati o tutti sazi
    n_hungry=0
    n_not_hungry=0
    for x in list_dog:
        if x.is_hungry==False:
            n_not_hungry+=1
        else:
            n_hungry+=1
    
    if n_not_hungry==len(list_dog):
        return "My dogs are not hungry."
    elif n_hungry==len(list_dog):
        return "My dogs are hungry."
    else:
        return f"{n_hungry} of them are hungry, while {n_not_hungry} are not."

    
print(f"I have {len(list_dog)} dogs.")
for x in list_dog:
    print(f"{x.name} is {x.age}.")
print(f"And they are all {Tobia.species}, of course.")

print("\n",check_status(list_dog))                # Sono tutti affamati di default
Argo.eat()
print(check_status(list_dog))                     # Ora Argo non è affamato 
feed_all_dogs()
print(check_status(list_dog))                     # Ora nessuno è affamato

I have 3 dogs.
Tobia is 7.
Maya is 3.
Argo is 13.
And they are all mammal, of course.

 My dogs are hungry.
2 of them are hungry, while 1 are not.
My dogs are not hungry.
