1\. Write the following as a list comprehension

In [14]:
# 1
ans = []
for i in range(3):
    for j in range(4):
        ans.append((i, j))
print (ans)

# 2
ans = map(lambda x: x*x, filter(lambda x: x%2 == 0, range(5)))
print (list(ans))


##Excercise 1

ans = [[x,y] for x in range(3) for y in range(4)]
print(ans)

##Excercise 2

ans = [ x**2 for x in range(5) if x%2 ==0]
print(ans)



[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]
[0, 4, 16]
[[0, 0], [0, 1], [0, 2], [0, 3], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0], [2, 1], [2, 2], [2, 3]]
[0, 4, 16]


2\. Convert the following function into a pure function with no global variables or side effects

In [26]:
x = 5
def f(alist):
    for i in range(x):
         alist.append(i)
    return alist

alist = [1,2,3]
ans = f(alist)
print (ans)
print (alist) # alist has been changed!


def f_ans(alist_ans,num):
    aux = list(alist_ans)
    for i in range(num):
        aux.append(i)
    return aux

alist = [1,2,3]
ans = f_ans(alist,2)
print (ans)
print (alist) 


[1, 2, 3, 0, 1, 2, 3, 4]
[1, 2, 3, 0, 1, 2, 3, 4]
[1, 2, 3, 0, 1]
[1, 2, 3]


3\. Write a `decorator` hello that makes every wrapped function print “Hello!”, i.e. something like:

```python
@hello
def square(x):
    return x*x
```



In [4]:
def hello(func):
    def wrapper(*x):
        print("Hello!")
        func(*x)
        print("Hello!")
    return wrapper

@hello
def square(x):
    print(x)


square(5)


Hello!
5
Hello!


4\. Write the factorial function so that it a) does and b) does not use recursion.

In [49]:
##a
def factorial_rec(num):
    fact_rec = 1
    if num == 0:
        return 1
    else:  
        return num*factorial_rec(num-1)

##b
def factorial(num):
    fact = 1
    for i in range(1,num+1):
        fact = fact*i
    return fact

print(factorial_rec(3))
print(factorial(3))


6
6


In [50]:
%timeit factorial_rec(200)
%timeit factorial(200)

24.8 µs ± 27.1 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
11.4 µs ± 25.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


5\. Use HOFs (zip in particular) to compute the weight of a circle, a disk and a sphere, assuming different radii and different densities:

```python
densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
radii = [1,2,3]
```

where the entries of the dictionary's values are the linear, superficial and volumetric densities of the materials respectively.

In particular define a list of three lambda functions using a comprehension that computes the circumference, the area and the volume for a given radius.


In [35]:
from numpy import pi
from numpy import empty
densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
lineales = [elem[0] for elem in densities.values()]
areas = [elem[1] for elem in densities.values()]
volumenes = [elem[2] for elem in densities.values()]

sol = empty((3, 3, 3))

radii = [1,2,3]
funciones = [lambda x: round(2*pi*x), lambda x: round(pi*x*x/4), lambda x: round((4/3)*pi*x*x*x)]
i = 0
for x, y in zip(ordenado, funciones):
    j=0
    for r in radii:
        sol[i][j][0] = y(r)*x[0]
        sol[i][j][1] = y(r)*x[1]
        sol[i][j][2] = y(r)*x[2]
        j=j+1
    i=i+1

print(sol)


[[[3.00e+00 1.80e+01 9.00e+01]
  [6.50e+00 3.90e+01 1.95e+02]
  [9.50e+00 5.70e+01 2.85e+02]]

 [[1.00e+00 4.00e+00 2.00e+01]
  [3.00e+00 1.20e+01 6.00e+01]
  [7.00e+00 2.80e+01 1.40e+02]]

 [[8.00e+00 2.00e+01 1.20e+02]
  [6.80e+01 1.70e+02 1.02e+03]
  [2.26e+02 5.65e+02 3.39e+03]]]


6\. Edit the class defintion to add an instance attribute of is_hungry = True to the Dog class. Then add a method called eat() which changes the value of is_hungry to False when called. Figure out the best way to feed each dog and then output “My dogs are hungry.” if all are hungry or “My dogs are not hungry.” if all are not hungry. The final output should look like this:

`I have 3 dogs. 
Tom is 6. 
Fletcher is 7. 
Larry is 9. 
And they're all mammals, of course. 
My dogs are not hungry.
`

```python
# Parent class
class Dog:

    # Class attribute
    species = 'mammal'

    # Initializer / Instance attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)

    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)

# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)
```

In [118]:
# Parent class
class Dog:

    # Class attribute
    species = 'mammal'
    is_hungry = True

    # Initializer / Instance attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)
    
    # instance method new
    def eat(self):
        self.is_hungry = False
        return "{} eats".format(self.name)

    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)

# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)
    
class GermanShepard(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)
    



In [142]:
perro1 = Bulldog("Sombra",9)
perro2 = RussellTerrier("Fido",2)
perro3 = GermanShepard("Rex",7)

perros = [perro1,perro2,perro3]

print("I have", len(perros), "dogs")
for x in range(len(perros)):
    print(perros[x].name ,"is",perros[x].age)
    
print("And they are all",perro1.species + "s", "of course")

for x in range(len(perros)):
    perros[x].eat()

all_hungry = False
for x in range(len(perros)):
    if perros[x].is_hungry == True:
        all_hungry = True
            
if all_hungry == True:
    print("My dogs are hungry")
else:
    print("My dogs are not hungry")

I have 3 dogs
Sombra is 9
Fido is 2
Rex is 7
And they are all mammals of course
My dogs are not hungry
