# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [9]:
l=np.array(np.random.random(20))

file_name = "simple_data.txt"
with open(file_name, mode='w') as f:
    f.write(str(l))

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [14]:
m=np.array(np.random.random(25)).reshape(5,5)

file_name="data.txt"
with open(file_name, mode='w') as f:
    f.write(str(m))

3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [32]:
file_name = "data.txt"

tmp=[]
with open(file_name, mode='r') as f:
    for line in f:
        tmp.append(line)
    f.close()
            
print(tmp,'\n')

with open(file_name, mode='r') as f:
    for line in f:
        print(line)
    f.close()



['[[0.18749851 0.8240065  0.6991606  0.14090425 0.64800662]\n', ' [0.25730155 0.5224074  0.10683465 0.69719799 0.53047295]\n', ' [0.3323055  0.23838403 0.57410468 0.3227349  0.7993    ]\n', ' [0.5212025  0.97901259 0.45016998 0.99225859 0.44737159]\n', ' [0.45911751 0.75428201 0.99929785 0.98895883 0.82780793]]'] 

[[0.18749851 0.8240065  0.6991606  0.14090425 0.64800662]

 [0.25730155 0.5224074  0.10683465 0.69719799 0.53047295]

 [0.3323055  0.23838403 0.57410468 0.3227349  0.7993    ]

 [0.5212025  0.97901259 0.45016998 0.99225859 0.44737159]

 [0.45911751 0.75428201 0.99929785 0.98895883 0.82780793]]


4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.