# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [2]:
l=np.array(np.random.random(20))

file_name = "simple_data.txt"
with open(file_name, mode='w') as f:
    f.write(str(l))
    f.close()
    
with open(file_name, mode='r') as f:
    for line in f:
        print(line)
    f.close()

[0.52783647 0.53200935 0.72634312 0.76236392 0.67984278 0.5963085

 0.33332188 0.19755985 0.4116326  0.30324869 0.78821738 0.53311821

 0.67818502 0.98979534 0.62163053 0.99255913 0.67117963 0.50156164

 0.6458445  0.39503879]


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [5]:
m=np.array(np.random.random(25)).reshape(5,5)

file_name="data.txt"
with open(file_name, mode='w') as f:
    f.write(str(m))
    
with open(file_name, mode='r') as f:
    for line in f:
        print(line)
    f.close()

[[0.09288546 0.42841868 0.44140338 0.82601749 0.32005014]

 [0.03872312 0.79695505 0.90517267 0.01374686 0.2870908 ]

 [0.35068881 0.22920803 0.35928947 0.22381331 0.82647262]

 [0.48043074 0.88248794 0.78608671 0.13758236 0.82673724]

 [0.18791625 0.07558352 0.69184373 0.43007171 0.80270563]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [13]:
import csv
file_name = "data.txt"

tmp=[]
with open(file_name, mode='r') as f:
    for line in f:
        tmp.append(line)
    f.close()
            
print(tmp,'\n')

with open(file_name, mode='r') as f:
    for line in f:
        print(line)
    f.close()


with open('data.csv', mode='w') as data_file:
    data_writer = csv.writer(data_file, delimiter=',', quotechar='"')
    for i in tmp:
        data_writer.writerow((tmp[i])
   
        



['[[0.09288546 0.42841868 0.44140338 0.82601749 0.32005014]\n', ' [0.03872312 0.79695505 0.90517267 0.01374686 0.2870908 ]\n', ' [0.35068881 0.22920803 0.35928947 0.22381331 0.82647262]\n', ' [0.48043074 0.88248794 0.78608671 0.13758236 0.82673724]\n', ' [0.18791625 0.07558352 0.69184373 0.43007171 0.80270563]]'] 

[[0.09288546 0.42841868 0.44140338 0.82601749 0.32005014]

 [0.03872312 0.79695505 0.90517267 0.01374686 0.2870908 ]

 [0.35068881 0.22920803 0.35928947 0.22381331 0.82647262]

 [0.48043074 0.88248794 0.78608671 0.13758236 0.82673724]

 [0.18791625 0.07558352 0.69184373 0.43007171 0.80270563]]


'\nwith open(\'data.csv\', mode=\'w\') as data_file:\n    data_writer = csv.writer(data_file, delimiter=\',\', quotechar=\'"\')\n    for i in tmp:\n        data_writer.writerow((tmp[i])\n'

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.