# OSEMN Exercises

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [22]:
from random import random

rnd = [str(random()) for i in range(5)]

# save list into file simple_data.txt
with open('simple_data.txt', 'w') as f:
    f.write('\n'.join(rnd))

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [49]:
mat = np.random.rand(5,5)
print(mat)

# save matrix into file data.txt
file_name = "/home/matteo/Scrivania/LaboratoryOfComputationalPhysics_Y4/data.txt"
with open(file_name, mode='w') as f:
    for line in range(mat.shape[0]):
        f.write(str(mat[line])+"\n")

[[0.16287715 0.41565358 0.95498625 0.9636837  0.8761696 ]
 [0.11563493 0.53442197 0.29981572 0.66780457 0.32213384]
 [0.5471289  0.10710382 0.11136608 0.02720446 0.3343954 ]
 [0.51051693 0.07319711 0.41098027 0.88460148 0.13779856]
 [0.7491453  0.95475425 0.87945377 0.87780966 0.66886018]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.